#!/bin/bash
#$ -cwd
#$ -o /dev/null
#$ -e /dev/null
# Set the number of processes here:
#$ -pe smp 8
# Set the number of processors (if different from the above) here:
setenv OMP_NUM_THREADS 16
# Change the name of the execuatable and the file name from here:
./row_wise_v1 ../../data/simulated/9.txt > output.txt
